#travis configuration for coverage testing
language: c

#sudo: false # only for faster builds

# install lcov to coveralls conversion + upload tool
#- gem install coveralls-lcov


#before_script: 
#- cd ${TRAVIS_BUILD_DIR}
#- lcov --directory . --zerocounters

# Compiler selection
compiler:
  - clang
  - gcc


# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - make && ./test-library.out


#after_success:
#- cd ${TRAVIS_BUILD_DIR}
#- lcov --directory . --capture --output-file coverage.info # capture coverage info
#- lcov --remove coverage.info 'tests/*' '/usr/*' 'test-library*' --output-file coverage.info # filter out system and test code
#- lcov --list coverage.info # debug before upload
#- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls.. for a private repo using a token
#- coveralls-lcov  coverage.info #for open source 


