# Codecov configuration for C/C++ Testing Example
# This file configures how Codecov processes and displays coverage reports

coverage:
  # Set coverage targets and thresholds
  status:
    project:
      default:
        target: 80%  # Expect at least 80% coverage
        threshold: 5%  # Allow 5% decrease in coverage
    patch:
      default:
        target: 80%  # New code should have 80% coverage
        
  # Round coverage to 2 decimal places
  precision: 2
  round: down
  
  # Coverage range for color coding
  # red: 0-60%, yellow: 60-80%, green: 80-100%
  range: "60...100"

# Parse additional files for coverage
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# Comment configuration for pull requests
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

# Ignore certain files/paths from coverage
ignore:
  - "test-*.c"
  - "tests/**/*"
  - "build/**/*"

# Flag configuration for different test suites
flags:
  unittests:
    paths:
      - lib.c
    carryforward: false